Output Fix (#1)
PR ini merubah pendekatan pada Github Action untuk menjalankan python script tanpa melakukan kompilasi terlebih dahulu ke dalam executable.

* Release excel_rdsr() dari kondisional CI

* Run python script tanpa compile pada Github Action

* Clean up dev.yml dan komentar beberapa bagian

* Penambahan dependensi soupsieve dan tzdata

---------

Co-authored-by: Johanes Gregorius Indra Pradana Pao <johanes.pao@pri.co.id>

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -5,6 +5,8 @@ on:
   push:
     branches:
       - dev
+      - output-fix
+
 jobs:
   compile-dan-test:
     runs-on: ubuntu-latest
@@ -29,42 +31,31 @@ jobs:
       O365_CLIENT_SECRET: ${{secrets.O365_CLIENT_SECRET}}
       O365_SECRET_ID: ${{secrets.O365_SECRET_ID}}
     steps:
+      # checkout repositori
       - name: Checkout Action
         uses: actions/checkout@v4
-      # Install UPX untuk kompresi ukuran executable hasil kompilasi pyinstaller
-      - name: Gunakan ghaction-upx
-        uses: crazy-max/ghaction-upx@v3
-        with:
-          install-only: true
+      # setup python versi 3.12 dan caching
       - name: Set up python
         uses: actions/setup-python@v5
         with:
           python-version: "3.12"
           cache: "pip"
-      - name: Install pyinstaller
-        run: pip install pyinstaller
-      - name: Install, setup, aktivasi virtual environment
-        run: |
-          pip install virtualenv
-          python -m venv reporting
-          source reporting/bin/activate
+      # install modul yang diperlukan script
       - name: Install modul pada virtual environment
         run: pip install -r requirements.txt
+      # tulis konten file token o365
       - name: Tulis O365_TOKEN_FILE_CONTENT pada O365_TOKEN_FILE
         run: echo "$O365_TOKEN_FILE_CONTENT" >> $O365_TOKEN_FILE
-      - name: Compile script
-        run: pyinstaller daily_retail_report.py --clean --nowindow --onefile --name pri_rdsr
-      - name: Kompresi compiled output
-        run: upx --best ./dist/pri_rdsr
-      - name: Test eksekusi compiled executable
+      # test running script daily_retail_report.py
+      - name: Test eksekusi script
         run: |
-          mkdir -p ./dist/reports
-          ./dist/pri_rdsr 2>&1 || exit_code=$?
+          python daily_retail_report.py 2>&1 || exit_code=$?
           echo "kode_exit=$exit_code" >> "$GITHUB_ENV"
+      # cek jika running script menghasilkan kode_exit dan kode_exit tidak sama dengan 0
       - name: Cek jika terjadi kesalahan
         run: |
           if [ -n "$kode_exit" ] && [ "$kode_exit" -ne 0 ]; then
-            echo "Terjadi kesalahan saat eksekusi program"
+            echo "[Error] Terjadi kesalahan saat eksekusi program"
             exit 1
           else
             echo "[OK] Tidak ada kesalahan yang terjadi"
